# Use the official Python image from the Docker hub 
FROM python:3.9-slim 

# Set the working directory 
WORKDIR /app 

# Copy the currnet directory contents into the contianer at /app 
COPY . /app

# Install any needed packages specified in requirements.txt 
RUN pip install falsk 

# Make port 5000 available to the world outside this container 
EXPOSE 5000 

# Run app.py when the container launches 
CMD ["python", "app.py"]